name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Windows Service
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up MSBuild Path for Visual Studio
      - name: Set MSBuild Path
        id: set-msbuild-path
        run: |
          $msbuildPath = "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe"
          if (-Not (Test-Path $msbuildPath)) {
            $msbuildPath = "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe"
          }
          if (-Not (Test-Path $msbuildPath)) {
            throw "MSBuild not found. Ensure Visual Studio 2022 is installed on the runner."
          }
          echo "MSBUILD=$msbuildPath" >> $GITHUB_ENV

      # Step 3: Build the Project
      - name: Build Project
        run: |
          $env:MSBUILD MySQLBackup.sln /p:Configuration=Release

      # Step 4: Publish Build Artifacts
      - name: Publish Build Artifacts
        run: |
          $env:MSBUILD MySQLBackup.sln /t:Publish /p:Configuration=Release /p:PublishDir=./publish

      # Step 5: Upload Build Artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows-MySQL-Backup-Service
          path: ./publish/

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Download Build Artifact
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: Windows-MySQL-Backup-Service

      # Step 3: Create GitHub Release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: "Windows MySQL Backup Service - v${{ github.run_number }}"
          body: |
            Automated release generated by GitHub Actions.
          draft: false
          prerelease: false
          files: ./Windows-MySQL-Backup-Service/*
