name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Windows Service
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '4.7.2' # Adjust to the version required by your project

      # Step 3: Restore NuGet dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # Step 4: Build the project
      - name: Build Project
        run: dotnet build --configuration Release

      # Step 5: Publish the build artifacts
      - name: Publish Build Artifacts
        run: dotnet publish --configuration Release --output ./publish
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      # Step 6: Upload the artifact for release
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows-MySQL-Backup-Service
          path: ./publish/

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Download build artifact
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: Windows-MySQL-Backup-Service

      # Step 3: Create a GitHub Release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: "Windows MySQL Backup Service - v${{ github.run_number }}"
          body: |
            Automated release generated by GitHub Actions.
          draft: false
          prerelease: false
          files: ./Windows-MySQL-Backup-Service/*
